Add some OSS docs
ginomessmer/mlsa-greenathon pull request #11
Opened 2021-04-25 09:15 UTC by Rishit-dagli

I plan on adding some docs to this repository to maintain the open-source spirit.

---

Closes #10

2021-04-25 18:15 UTC, ginomessmer commented on CONTRIBUTING.md
> +1. Fork the repo and create your branch from `master`.
Should be renamed to main.

```suggestion
1. Fork the repo and create your branch from `main`.
```

2021-04-25 18:20 UTC, ginomessmer requested changes

2021-04-25 18:20 UTC, ginomessmer commented on CONTRIBUTING.md
> +1. Fork the repo and create your branch from `master`.
Should be renamed to main.

```suggestion
1. Fork the repo and create your branch from `main`.
```

2021-04-25 18:20 UTC, ginomessmer commented on CONTRIBUTING.md
> +5. Make sure your code lints.
Even though the current code linter checks for accessibility issues, should we consider adding a special note about A11Y?

2021-04-26 02:21 UTC, Rishit-dagli commented on CONTRIBUTING.md
> +5. Make sure your code lints.
I think accessibility linting should be covered under point 5, but we could add it as a separate bullet too?

2021-04-26 19:20 UTC, ginomessmer commented on CONTRIBUTING.md
> +5. Make sure your code lints.
I think you're right. Though I've been thinking about e.g. [Accessibility Insights](https://accessibilityinsights.io/) but we can also consider it at a later date. What do you think?

2021-04-26 19:23 UTC, ginomessmer approved these changes

2021-04-26 19:32 UTC, merged