Create an action to check markdown links for blog
ginomessmer/mlsa-greenathon pull request #3
Opened 2021-04-21 13:01 UTC by Rishit-dagli

Creates an action to check for broken links on the blogs

2021-04-21 13:07 UTC, ginomessmer commented
Thanks for setting up this PR. @Rishit-dagli if you are planning to edit the readme, feel free to reuse the one I created in #2:

https://github.com/ginomessmer/mlsa-greenathon/blob/6c8ed9ed885e0f116b416ba0011ef58e96fb2f9d/README.md

2021-04-22 12:28 UTC, ginomessmer commented
@Rishit-dagli I notice that the action doesn't run successfully, perhaps it's a formatting issue? Are you able to take a look at it?

https://github.com/ginomessmer/mlsa-greenathon/actions/runs/770727203/workflow

2021-04-22 12:29 UTC, ginomessmer requested changes

2021-04-22 12:29 UTC, ginomessmer commented on .github/workflows/markdown-links.yml
> +paths:
@Rishit-dagli I notice that the action doesn't run successfully, perhaps it's a formatting issue? Are you able to take a look at it?

https://github.com/ginomessmer/mlsa-greenathon/actions/runs/770727203/workflow

2021-04-22 13:21 UTC, Rishit-dagli commented on .github/workflows/markdown-links.yml
> +paths:
Ah, thanks for pointing this out. I copied this from  another of my projects and seems copy-pasting messed up some formatting

2021-04-22 14:04 UTC, ginomessmer approved these changes

2021-04-22 14:04 UTC, merged